inherits = "ayu_evolve"

"ui.virtual.jump-label" = { fg = "red", modifiers = ["bold"] }
"ui.picker.header.column.active" = { underline.style = "line" }
"ui.statusline" = { bg = "dark_gray" }
"ui.window" = "gray"
# for pickers, mostly
"ui.text.directory" = "cyan"

# same as evolve (inherited from dark) but no italic
"comment" = { fg = "gray" } 
# same as evolve but no italic
"type.builtin" = { fg = "blue" }

[palette]
black = "#131721" # bring back lighter black from ayu_dark
red = "#ff5540" # tone down red a bit

# from ghostty's ayu
green = "#b8cc52"
yellow = "#e7c547"
